### ISSUE TITLE
4.1 Boîte de délimitation

### ISSUE THREAD

**Issue by Davidferl** [NathPaquet/Infographie_IFT-3100#16]
Une option permet de dessiner les arêtes d’une boîte d’une taille juste assez grande pour envelopper tous les sommets d’un modèle 3D pour chaque type de modèle qu’il est possible d’utiliser avec l’application.

**Comment by cnator1** [comment]
prendre le mesh d'un sceneobject : regarder le min/max des positions x,y,z, ensuite creer une nouvelle primite ofprimitivebox
