### ISSUE TITLE
6.4 Cubemap

### ISSUE THREAD

**Issue by Davidferl** [NathPaquet/Infographie_IFT-3100#29]
Il existe au moins 1 texture de type cubemap qui est utilisée dans le rendu d’au moins 1 élément visuel d’une scène.

**Comment by NathPaquet** [comment]
Cubemap skybox space
![image](https://github.com/NathPaquet/Infographie_IFT-3100/assets/73801331/e94115da-e4a2-4fa0-a850-59c3cc1d12a3)
![image](https://github.com/NathPaquet/Infographie_IFT-3100/assets/73801331/1d1cf802-67a4-4b9c-a142-c2ff26e6b43d)
