### ISSUE TITLE
7.1 Modèles d'illumination

### ISSUE THREAD

**Issue by Davidferl** [NathPaquet/Infographie_IFT-3100#31]
Le rendu d’une ou plusieurs géométrie est fait à partir d’au moins 3 modèles d’illumination différents parmi les 4 classiques : Lambert, Gouraud, Phong et Blinn-Phong.

**Comment by NathPaquet** [comment]
Faire avec des shadder et voir le cours du 21 mars 2024 (On a des exemples dans les exemples du prof)
